services:
  selenium:
    image: selenium/standalone-chrome:4.35.0
    shm_size: 2gb
    ports:
      - "4444:4444"
    tmpfs:
      - /tmp:exec
    environment:
      - SE_BROWSER_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://selenium:4444/status >/dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - monitor-net

  futapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futapp
    ports:
      - "8080:8080"
    environment:
      - WEBDRIVER_URL=http://selenium:4444/wd/hub
    depends_on:
      selenium:
        condition: service_healthy
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Puerto para acceder a la UI de Prometheus
    volumes:
      # Monta el archivo de configuraci√≥n local en el path interno de Prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitor-net # Debe estar en la misma red que futapp

networks:
  monitor-net:
    driver: bridge
