scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: desapp-grupoe-futapi
    scheme: https
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ["desapp-grupoe-futapi-production.up.railway.app"]
